
services:
  # --- THE CACHE ---
  xhdh-redis:
    image: redis:latest
    container_name: xhdh-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s  
      timeout: 3s
      retries: 5
    networks:
      - xhdh-network

  # --- THE APPLICATION ---
  xhdh-api:
    build: .
    image: xhdh-backend:latest
    container_name: xhdh-backend
    ports:
      - "8000:8000"
    depends_on:
      xhdh-redis:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      SPRING_DATA_REDIS_HOST: xhdh-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_SSL_ENABLED: "false" # Local Docker doesn't use SSL
      SPRING_DATA_REDIS_PASSWORD: "" 

      SERVER_PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    networks:
      - xhdh-network
    volumes:
      - ./.env:/app/.env

networks:
  xhdh-network:
    driver: bridge