name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/xhdh
            docker compose pull
            docker compose up -d